const quotes = [
    "Dream big, work even harder.",
    "Happiness is a choice daily.",
    "Believe in yourself and grow.",
    "Life begins outside your comfort.",
    "Kindness costs nothing, spread everywhere.",
    "Success starts with small steps.",
    "Gratitude turns chaos into clarity.",
    "Courage conquers fear, embrace it.",
    "Actions speak louder than words.",
    "Love fiercely, live without regret.",
    "Mistakes are lessons in disguise.",
    "Joy comes in small moments.",
    "Strength grows through life's challenges.",
    "Patience is bitter, reward sweet.",
    "Perseverance turns dreams into reality.",
    "Listen more, talk less often.",
    "Faith moves mountains, stay steadfast.",
    "Happiness blooms from within, always.",
    "Adventure awaits, step into unknown.",
    "Chase dreams, not fleeting trends.",
    "Every journey begins with courage.",
    "Kind words can heal hearts.",
    "Time flies, make moments count.",
    "Passion fuels purpose, ignite it.",
    "Forgive others, free your soul.",
    "Humility keeps success in balance.",
    "Learn something new each day.",
    "Hope anchors the soul's strength.",
    "Smile brightens even darkest days.",
    "Peace begins within, choose calm.",
    "Create beauty wherever you go.",
    "Your mindset shapes your destiny.",
    "Hard work beats natural talent.",
    "Persistence breaks walls of doubt.",
    "Compassion connects humanity, stay kind.",
    "Be bold, live without limits.",
    "Doubt kills more dreams than failure.",
    "Energy flows where focus goes.",
    "Greatness starts with simple actions.",
    "Live authentically, embrace true self.",
    "Challenges build resilience, not weakness.",
    "Celebrate progress, not just goals.",
    "Simplicity reveals the ultimate sophistication.",
    "Love grows where kindness thrives.",
    "Change begins with one step.",
    "Wisdom grows with age, embrace.",
    "Time wasted is opportunity lost.",
    "Hustle hard, success will follow.",
    "Peace exists in the present."
  ];
  function displayRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];
    document.getElementById("quote").innerText = randomQuote;
  }